import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router-dom';
import { Provider } from 'react-redux';
import { renderRoutes } from 'react-router-config';
import Routes from '../client/routes';

const VHConfig = require('../config');

export default async (req, store, context) => {
  store.getState();

  const content = renderToString(
    <Provider store={store}>
      <StaticRouter location={req.path} context={context}>
        <div>{renderRoutes(Routes)}</div>
      </StaticRouter>
    </Provider>,
  );

  return `<!DOCTYPE html><html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Primary Meta Tags -->
    <title>Test Page</title>
    <meta name="title" content="">
    <meta name="description" content="">

    <!-- Open Graph / Facebook -->
    <meta property="og:url" content="">
    <meta property="og:title" content="">
    <meta property="og:description" content="Page Test">


    <script data-react-helmet="true" type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@graph":
      [
        {
          "@type": "WebSite",
          "url": "https://www.vanhack.com",
          "potentialAction":
            {
              "@type": "SearchAction",
              "target": "https://www.vanhack.com/jobs/{search_term_string}",
              "query-input": "required name=search_term_string"
            }
         }
      ]
    }
    </script>

    <script data-react-helmet="true" type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebPage",
        "mainEntityOfPage": {
          "@type": "SearchResultsPage",
          "name": "Page Test",
          "description": "Page Test",
          "relatedLink":
          [
            "https://www.vanhack.com/jobs/net-jobs",
            "https://www.vanhack.com/jobs/in-canada",
            "https://www.vanhack.com/jobs/remote-jobs",
            "https://www.vanhack.com/jobs/java-jobs-in-canada",
            "https://www.vanhack.com/jobs/node-jobs-in-canada",
            "https://www.vanhack.com/jobs/react-jobs-in-canada",
            "https://www.vanhack.com/jobs/web-developer-jobs-in-canada"
          ]
        }
      }
    </script>

    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "url":"https://www.vanhack.com",
        "name":"VanHack",
        "legalName":"VanHack Technologies Inc.",
        "logo":"https://vanhackblobstorageprod.blob.core.windows.net/autogenerated/vanhack-small.png",
        "sameAs":[
          "https://www.linkedin.com/company/vanhack/mycompany/",
          "https://www.facebook.com/govanhack/",
          "https://www.instagram.com/govanhack/",
          "https://www.youtube.com/channel/UCmg0eAiV7f8LZf8vePG1tlA",
          "https://twitter.com/GoVanHack"
        ],
        "contactPoint": [
          {
            "@type": "ContactPoint",
            "email": "contact@vanhack.com",
            "contactType": "customer service",
            "contactOption": "TollFree"
          }
        ]
      }
    </script>
    <link rel="canonical" href="https://vanhack.com">
    <link rel="icon" href="https://www.vanhack.com/wp-content/uploads/2018/11/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/react-phone-number-input@3.x/bundle/style.css"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'  rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap'  rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Inter::300,400,500,700&display=swap' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;700&display=swap" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@700&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://vanhackblobstorageprod.blob.core.windows.net/scripts/amplitude-embed.js"></script>
    <base href='/static-desktop/' />
    <style>
      body, html {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .pac-container {
        /* Disclaimer: not needed to show 'powered by Google' if also a Google Map is shown */

        z-index: 90000;
    }

    /*Styling for the lines connecting the labels to the slices*/
    polyline{
        opacity: .3;
        stroke: black;
        stroke-width: 2px;
        fill: none;
        shape-rendering: geometricPrecision;
    }

    /* styling for the donut slices*/
    path {
        shape-rendering: geometricPrecision;
    }

    /* Make the percentage on the text labels bold*/
    .labelName tspan {
        font-style: normal;
        font-weight: 700;
    }

    /* In biology we generally italicise species names. */
    .labelName {
        font-size: 0.8em;
        font-style: italic;
    }
    </style>

  </head>
  <body>
    <div id="root">${content}</div>

    <script src="bundle-cli.js"></script>
    <script type="text/javascript" src="https://secure.perk0mean.com/js/176095.js"></script>
    <noscript><img src="https://secure.perk0mean.com/176095.png" alt="" style="display:none;" /></noscript>
    <!-- Google Tag Manager (noscript) -->

      <!-- End Google Tag Manager (noscript) -->
      <!-- Global site tag (gtag.js) - Google Analytics -->

    <script src="${process.env.BROWSER_REFRESH_URL}"></script>
  </body>
</html>`;
};
